services:

  emby:
    image: emby/embyserver:4.9.1.0
    container_name: emby
    labels:
      traefik.enable: true
      traefik.http.services.emby.loadbalancer.server.port: 8096
      backup.enable: true
    environment:
      UID: 1000
      GID: 1000
      GIDLIST: ${UID_VIDEO},${UID_RENDER}
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8096/emby/system/info/public || exit 1"]
      start_period: 60s
      start_interval: 5s
      interval: 60s
      timeout: 5s
      retries: 3
    volumes:
    - ${DATA_FOLDER_PATH:-.}${DATA_FOLDER_PATH:+/emby}/config:/config
    - ${TV_SHOW_DIRECTORY:-./tvshow}:/mnt/tvshow:ro
    - ${MOVIE_DIRECTORY:-./movie}:/mnt/movie:ro
    - ${PUBLIC_DIRECTORY:-./public}/Medien:/mnt/media:ro
    - ${LEVIN_DIRECTORY:-./levin}/Bilder:/mnt/pictures/levin:ro
    - ${KATRIN_DIRECTORY:-./katrin}/Fotos:/mnt/pictures/katrin:ro
    - ${SHARE_DIRECTORY:-./share}/Fotos:/mnt/pictures/share:ro
    - ${SHARE_DIRECTORY:-./share}/Musik:/mnt/music:ro
    devices:
    - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    networks:
    - traefik
    restart: unless-stopped
