services:

  grafana:
    image: grafana/grafana-enterprise:11.3.1
    container_name: grafana
    labels:
      traefik.enable: true
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      start_period: 60s
      start_interval: 5s
      interval: 60s
      timeout: 5s
      retries: 3
    user: 0:0
    volumes:
    - ${DATA_FOLDER_PATH:-.}${DATA_FOLDER_PATH:+/grafana}/data:/var/lib/grafana
    networks:
    - traefik
    - prometheus
    restart: unless-stopped
