---
title: "Dashboard"
subtitle: "Lanty"
logo: "assets/icon-any.png"

header: false
footer: '<p>Theme made with <span class="has-text-danger">❤️</span> by <a href="https://github.com/WalkxCode">Walkx</a></p>'

stylesheet:
- "assets/custom.css"

columns: "3"
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "/assets/wallpaper.jpg"
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "/assets/wallpaper.jpg"

services:
- name: "Services"
  icon: "fas fa-cloud"
  items:
  - name: "Authentik"
    icon: "tools/authentik.png"
    subtitle: "Open-Source IdP (Identity Provider) and SSO (single sign on)"
    #tag: "setup"
    url: "https://authentik.jest-home.de"
  - name: "Bitwarden"
    icon: "tools/bitwarden.png"
    subtitle: "Password manager for passwords and passkeys"
    #tag: "setup"
    url: "https://bitwarden.jest-home.de"
  - name: "cAdvisor"
    icon: "tools/cadvisor.png"
    subtitle: "Provides container resource usage and performance"
    #tag: "setup"
    url: "https://cadvisor.jest-home.de"
  - name: "DDNSUpdater"
    icon: "tools/ddnsupdater.png"
    subtitle: "Update DNS records for multiple providers"
    #tag: "setup"
    url: "https://ddnsupdater.jest-home.de"
  - name: "Emby"
    icon: "tools/emby.png"
    subtitle: "Personal media library manager and streaming provider"
    #tag: "setup"
    url: "https://emby.jest-home.de"
  - name: "Filebrowser"
    icon: "tools/filebrowser.png"
    subtitle: "Filebrowser for managing your files"
    #tag: "setup"
    url: "https://filebrowser.jest-home.de"
  - name: "Firefly III"
    icon: "tools/firefly.png"
    subtitle: "Personal finances manager"
    #tag: "setup"
    url: "https://firefly.jest-home.de"
  - name: "Grafana"
    icon: "tools/grafana.png"
    subtitle: "Open source analytics & monitoring"
    #tag: "setup"
    url: "https://grafana.jest-home.de"
  - name: "Homeassistant"
    icon: "tools/homeassistant.png"
    subtitle: "Open source home automation"
    #tag: "setup"
    url: "https://homeassistant.jest-home.de"
  - name: "Pi-hole"
    icon: "tools/pihole.png"
    subtitle: "Adblocker for your home network"
    #tag: "setup"
    url: "https://pihole.jest-home.de"
  - name: "Portainer"
    icon: "tools/portainer.png"
    subtitle: "Container management software"
    #tag: "setup"
    url: "https://portainer.jest-home.de"
  - name: "Prometheus"
    icon: "tools/prometheus.png"
    subtitle: "Open source monitoring system"
    #tag: "setup"
    url: "https://prometheus.jest-home.de"
  - name: "pyLoad"
    icon: "tools/pyload.png"
    subtitle: "Download manager"
    #tag: "setup"
    url: "https://pyload.jest-home.de"
  - name: "Traefik"
    icon: "tools/traefik.png"
    subtitle: "Reverse proxy & load balancer"
    #tag: "setup"
    url: "https://traefik.jest-home.de"
  - name: "Unifi Gateway"
    icon: "tools/unifi.png"
    subtitle: "Network gateway powered by Unifi"
    #tag: "setup"
    url: "https://unifi.jest-home.de"
