http:
  routers:
    pihole:
      entryPoints:
      - websecure
      service: pihole-app
      rule: Host(`pihole.{{ env "DOMAIN" }}`)
      tls:
        certResolver: caresolver

  services:
    pihole-app:
      loadBalancer:
        servers:
        - url: http://{{ env "PIHOLE_IP" }}
        passHostHeader: true
