- name: setup server
  hosts: jest

  tasks:
    - name: change-system-passwords
      ansible.builtin.import_tasks: ../../tasks/change-passwords.yaml

    - name: configuration ssh/sshd
      ansible.builtin.import_tasks: ../../tasks/configure-sshd.yaml

    - name: setup unattended-upgrades
      ansible.builtin.import_tasks: ../../tasks/setup-unattended-upgrades.yaml

    - name: setup disks
      ansible.builtin.import_tasks: ../tasks/setup-disks.yaml

    - name: setup docker
      ansible.builtin.import_tasks: ../tasks/setup-docker.yaml
