- name: make getent group database available for templating
  ansible.builtin.getent:
    database: group
    split: ':'

- name: configure .env for services
  become: yes
  ansible.builtin.template:
    src: ../templates/service.env.j2
    dest: "{{ services.repository.directory }}/services/.env"

- name: deploy services
  become: yes
  community.docker.docker_compose_v2:
    project_src: "{{ services.repository.directory }}/services"
    env_files: .env
    remove_orphans: true
    state: present
  register: docker_compose_output
  when: services.start_services

- name: show service startup output
  ansible.builtin.debug:
    var: docker_compose_output
  when: services.start_services
