- name: check service repository is already cloned
  become: yes
  ansible.builtin.git:
    repo: "{{ services.repository.url }}"
    dest: "{{ services.repository.directory }}"
    clone: no
    update: no
  register: service_repo_status

- name: clone service repository if not cloned
  become: yes
  ansible.builtin.git:
    repo: "{{ services.repository.url }}"
    dest: "{{ services.repository.directory }}"
    version: "{{ services.repository.version }}"
  when: service_repo_status.changed

- name: update service repository if already cloned
  become: yes
  ansible.builtin.git:
    repo: "{{ services.repository.url }}"
    dest: "{{ services.repository.directory }}"
    version: "{{ services.repository.version }}"
    clone: no
    force: true
  when: not service_repo_status.changed
