- name: setup docker & docker compose
  become: true
  ansible.builtin.import_role:
    name: geerlingguy.docker
  vars:
    docker_edition: ce
    docker_packages:
    - docker-{{ docker_edition }}
    - docker-{{ docker_edition }}-cli
    - containerd.io
    #- "docker-{{ docker_edition }}-rootless-extras"
    - docker-buildx-plugin
    docker_packages_state: latest
    docker_service_manage: true
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_install_compose_plugin: true
    docker_compose_package: docker-compose-plugin
    docker_compose_package_state: latest
    docker_install_compose: false
    #docker_compose_version: "v2.29.2"
    #docker_compose_arch: "{{ ansible_architecture }}"
    #docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-{{ docker_compose_arch }}"
    #docker_compose_path: /usr/local/bin/docker-compose
    docker_add_repo: true
    docker_repo_url: https://download.docker.com/linux
    docker_apt_release_channel: stable
    # docker_apt_ansible_distribution is a workaround for Ubuntu variants which can't be identified as such by Ansible,
    # and is only necessary until Docker officially supports them.
    docker_apt_ansible_distribution: "{{ 'ubuntu' if ansible_distribution in ['Pop!_OS', 'Linux Mint'] else ansible_distribution }}"
    docker_apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'armhf' if ansible_architecture == 'armv7l' else 'amd64' }}"
    docker_apt_repository: "deb [arch={{ docker_apt_arch }} signed-by=/etc/apt/keyrings/docker.asc] {{ docker_repo_url }}/{{ docker_apt_ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
    docker_apt_ignore_key_error: true
    docker_apt_gpg_key: "{{ docker_repo_url }}/{{ docker_apt_ansible_distribution | lower }}/gpg"
    docker_apt_gpg_key_checksum: "sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570"
    docker_apt_filename: "docker"
    #docker_users: []
    docker_daemon_options:
      metrics-addr: 0.0.0.0:9323
