version: "1"

global:
  group-continue-on-error: true
  initialize: true
  log: /log/resticprofile.log
  scheduler: crond

groups:
  full:
  - service-data
  - levin
  - katrin
  - share
  - public

template:
  repository: "local:/{{ .Profile.Name }}_backup"
  password-file: "/run/secrets/{{ .Profile.Name }}_password"
  lock: /tmp/resticprofile-{{ .Profile.Name }}.lock
  prometheus-save-to-file: /prometheus/{{ .Profile.Name}}.prom

  backup:
    schedule: "02:00"
    schedule-permission: system
    schedule-log-wait: 30m
    schedule-log: /log/{{ .Profile.Name }}_backup
    check-after: true
    source:
      - "/{{ .Profile.Name }}"
    host: jest
    group-by: paths
    skip-if-unchanged: true

  retention:
    after-backup: true
    group-by: paths
    keep-daily: 14
    keep-weekly: 12
    keep-monthly: 6
    keep-yearly: 2
    prune: true

levin:
  inherit: template
levin-check:
  inherit: levin

katrin:
  inherit: template
katrin-check:
  inherit: katrin

share:
  inherit: template
share-check:
  inherit: share

public:
  inherit: template
public-check:
  inherit: public

service-data:
  inherit: template
  check:
    read-data: true
  # backup:
  #   run-before: |
  #     docker ps -q --filter "label=backup.enable=true" --filter "name=bitwarden" > /container && 
  #     docker stop $(cat /container)
  #   run-finally: docker start $(cat /container)
