version: "1"

global:
  group-continue-on-error: true
  initialize: true
  log: /log/resticprofile.log
  scheduler: crond

groups:
  full:
  - service-data
  - levin
  - katrin
  - share
  - public

template:
  lock: /tmp/resticprofile-{{ .Profile.Name }}.lock
  prometheus-save-to-file: /prometheus/resticprofile_{{ .Profile.Name}}.prom

  backup:
    schedule-permission: system
    schedule-log-wait: 30m
    schedule-log: /log/{{ .Profile.Name }}_backup
    check-after: true
    source:
      - "/{{ .Profile.Name }}"
    host: jest
    group-by: paths
    skip-if-unchanged: true

  retention:
    after-backup: true
    group-by: paths
    keep-daily: 14
    keep-weekly: 12
    keep-monthly: 6
    keep-yearly: 2
    prune: true

levin:
  inherit: template
  repository: "local:/levin_backup"
  password-file: "/run/secrets/levin_password"
  backup:
    schedule: "02:00"
levin-check:
  inherit: levin
  backup:
    schedule: ""
  check:
    schedule: "Sun 22:00"
    schedule-permission: system
    schedule-log-wait: 30m
    schedule-log: /log/{{ .Profile.Name }}_backup
    read-data: true

katrin:
  inherit: template
  repository: "local:/katrin_backup"
  password-file: "/run/secrets/katrin_password"
  backup:
    schedule: "02:00"
katrin-check:
  inherit: katrin
  backup:
    schedule: ""
  check:
    schedule: "Sun 22:00"
    schedule-permission: system
    schedule-log-wait: 30m
    schedule-log: /log/{{ .Profile.Name }}_backup
    read-data: true

share:
  inherit: template
  repository: "local:/share_backup"
  password-file: "/run/secrets/share_password"
  backup:
    schedule: "02:00"
share-check:
  inherit: share
  backup:
    schedule: ""
  check:
    schedule: "Sun 22:00"
    schedule-permission: system
    schedule-log-wait: 30m
    schedule-log: /log/{{ .Profile.Name }}_backup
    read-data: true

public:
  inherit: template
  repository: "local:/public_backup"
  password-file: "/run/secrets/public_password"
  backup:
    schedule: "02:00"
public-check:
  inherit: public
  backup:
    schedule: ""
  check:
    schedule: "Sun 22:00"
    schedule-permission: system
    schedule-log-wait: 30m
    schedule-log: /log/{{ .Profile.Name }}_backup
    read-data-subset: 5%

service-data:
  inherit: template
  repository: "local:/service-data_backup"
  password-file: "/run/secrets/service-data_password"
  check:
    read-data: true
  backup:
    schedule: "02:00"
    run-before: >-
      docker ps -q --filter "label=backup.enable=true" > /container &&
      docker ps -q --filter "name=bitwarden" >> /container &&
      echo "Stop all service containers for backup:" &&
      docker stop $(cat /container)
    run-finally: >-
      echo "Start all service containers stopped for backup:" &&
      docker start $(cat /container)
