
services:

  # No healthcheck possible. Only Go binary in container without built.in healthcheck
  unpoller:
    image: ghcr.io/unpoller/unpoller:v2.15.4
    container_name: unpoller
    labels:
      prometheus.scrape: true
      prometheus.port: 9130
    environment:
      UP_UNIFI_DEFAULT_URL: https://${UNIFI_GATEWAY_IP}
      UP_UNIFI_DEFAULT_USER: unpoller
      UP_UNIFI_DEFAULT_PASS: file:///run/secrets/unpoller_password
      UP_INFLUXDB_DISABLE: true
    secrets:
    - unpoller_password
    networks:
    - prometheus
    restart: unless-stopped

secrets:

  unpoller_password:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/unpoller}/password
