
services:

  unpoller:
    image: ghcr.io/unpoller/unpoller:v2.14.1
    container_name: unpoller
    labels:
      prometheus.scrape: true
      prometheus.port: 9130
    environment:
      UP_UNIFI_DEFAULT_URL: https://${UNIFI_GATEWAY_IP}
      UP_UNIFI_DEFAULT_USER: file:///run/secrets/unpoller_user
      UP_UNIFI_DEFAULT_PASS: file:///run/secrets/unpoller_password
      UP_INFLUXDB_DISABLE: true
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9130/health || exit 1"]
      start_period: 60s
      start_interval: 5s
      interval: 60s
      timeout: 5s
      retries: 3
    secrets:
    - unpoller_user
    - unpoller_password
    networks:
    - prometheus
    restart: unless-stopped

secrets:

  unpoller_user:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/unpoller}/user
  unpoller_password:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/unpoller}/password
