services:

  immichdb:
    image: tensorchord/pgvecto-rs:pg16-v0.3.0
    container_name: immichdb
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/immich_db_password
      POSTGRES_USER_FILE: /run/secrets/immich_db_user
      POSTGRES_DB_FILE: /run/secrets/immich_db_name
      POSTGRES_INITDB_ARGS: --data-checksums
    healthcheck:
      test: pg_isready --dbname=$(cat /run/secrets/immich_db_name) --username=$(cat /run/secrets/immich_db_user) || exit 1; Chksum="$(psql --dbname=$(cat /run/secrets/immich_db_name) --username=$(cat /run/secrets/immich_db_user) --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
    - "postgres"
    - "-c"
    - "shared_preload_libraries=vectors.so"
    - "-c"
    - "search_path='$$user', public, vectors"
    - "-c"
    - "logging_collector=on"
    - "-c"
    - "max_wal_size=2GB"
    - "-c"
    - "shared_buffers=512MB"
    - "-c"
    - "wal_compression=on"
    volumes:
    - ${DATA_FOLDER_PATH:-.}${DATA_FOLDER_PATH:+/immich}/database:/var/lib/postgresql/data
    secrets:
    - immich_db_user
    - immich_db_password
    - immich_db_name
    networks:
    - immich
    restart: unless-stopped

  immichredis:
    image: redis:7.4.1-alpine
    container_name: immichredis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    command:
    - --loglevel
    - warning
    volumes:
    - ${DATA_FOLDER_PATH:-.}${DATA_FOLDER_PATH:+/immich}/redis:/data
    networks:
    - immich
    restart: unless-stopped

  immichmachinelearning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.121.0
    container_name: immichmachinelearning
    environment:
      IMMICH_LOG_LEVEL: warn
      NO_COLOR: true
    volumes:
    - ${DATA_FOLDER_PATH:-.}${DATA_FOLDER_PATH:+/immich}/model-cache:/cache
    networks:
    - immich
    restart: unless-stopped

  immich:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:v1.121.0
    labels:
      traefik.enable: true
      prometheus.scrape: true
      prometheus.port: 8081
      prometheus.port2: 8082
    environment:
      TZ: Europe/Berlin
      IMMICH_LOG_LEVEL: warn
      NO_COLOR: true
      IMMICH_TRUSTED_PROXIES: 172.0.0.0/8
      DB_HOSTNAME: immichdb
      DB_USERNAME_FILE: /run/secrets/immich_db_user
      DB_PASSWORD_FILE: /run/secrets/immich_db_password
      DB_DATABASE_NAME_FILE: /run/secrets/immich_db_name
      REDIS_HOSTNAME: immichredis
      IMMICH_TELEMETRY_INCLUDE: all
    volumes:
    - ${DATA_FOLDER_PATH:-.}${DATA_FOLDER_PATH:+/immich}/upload:/usr/src/app/upload
    secrets:
    - immich_db_user
    - immich_db_password
    - immich_db_name
    networks:
    - traefik
    - prometheus
    - immich
    restart: unless-stopped
    depends_on:
    - immichdb
    - immichredis

secrets:

  immich_db_user:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/immich}/db_user
  immich_db_password:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/immich}/db_password
  immich_db_name:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/immich}/db_name

networks:
  immich:
