services:

  portainer:
    image: portainer/portainer-ce:2.24.0-alpine
    container_name: portainer
    labels:
      traefik.enable: true
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    healthcheck:
      test: ['CMD-SHELL', 'wget --quiet --tries=1 --spider http://localhost:9000/api/system/status || exit 1']
      start_period: 60s
      start_interval: 5s
      interval: 60s
      timeout: 5s
      retries: 3
    volumes:
      - ${DATA_FOLDER_PATH:-.}${DATA_FOLDER_PATH:+/portainer}/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - traefik
    restart: unless-stopped
