- name: change user passwords
  become: true
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ item.password | password_hash('sha512', 'R3U29A792974bu7k') }}"
  loop: "{{ users_update_password }}"
  loop_control:
    label: "{{ item.username }}"
