- name: configuration ssh/sshd
  become: true
  ansible.builtin.import_role: 
    name: devsec.hardening.ssh_hardening
  vars:
    ssh_hardening_enabled: true
    ssh_client_hardening: false
    ssh_server_hardening: true
    network_ipv6_enable: false
    ssh_server_enabled: true
    ssh_server_service_enabled: true
    ssh_use_dns: false
    ssh_client_compression: false
    ssh_compression: false
    ssh_client_password_login: false
    ssh_server_password_login: true
    ssh_server_ports: ["22"]
    ssh_client_port: "22"
    ssh_listen_to: [0.0.0.0]
    ssh_host_rsa_key_size: 4096
    ssh_host_certificates: []
    ssh_host_key_algorithms: []
    ssh_client_host_key_algorithms: []
    ssh_login_grace_time: 180s
    ssh_max_auth_retries: 3
    ssh_max_sessions: 3
    ssh_client_alive_interval: 300
    ssh_client_alive_count: 3
    ssh_permit_tunnel: "no"
    ssh_remote_hosts: []
    ssh_permit_root_login: "no"
    ssh_allow_tcp_forwarding: "no"
    ssh_gateway_ports: false
    ssh_allow_agent_forwarding: false
    ssh_x11_forwarding: false
    ssh_use_pam: true
    ssh_pubkey_authentication: true
    sshd_authenticationmethods: password
    ssh_gssapi_support: false
    ssh_gssapi_delegation: false
    ssh_deny_users: ""
    ssh_allow_users: ""
    ssh_deny_groups: ""
    ssh_allow_groups: ""
    ssh_authorized_keys_file: ""
    ssh_trusted_user_ca_keys_file: ""
    ssh_trusted_user_ca_keys: []
    ssh_authorized_principals_file: ""
    ssh_authorized_principals: []
    ssh_print_motd: false
    ssh_print_pam_motd: false
    ssh_print_last_log: true
    ssh_banner: false
    ssh_banner_path: /etc/ssh/banner.txt
    ssh_print_debian_banner: false
    sftp_enabled: true
    sftp_chroot: false
    sftp_umask: "0027"
    sftp_chroot_dir: /home/%u
    ssh_client_roaming: false
    ssh_server_match_user: false
    ssh_server_match_group: false
    ssh_server_match_address: false
    ssh_server_match_local_port: false
    ssh_server_permit_environment_vars: "no"
    ssh_server_accept_env_vars: ""
    ssh_max_startups: 10:30:60
    ssh_ps59: sandbox
    ssh_custom_selinux_dir: /etc/selinux/local-policies
    sshd_moduli_minimum: 2048
    ssh_challengeresponseauthentication: false
    ssh_server_revoked_keys: []
    ssh_custom_options: []
    sshd_custom_options: []
    sshd_syslog_facility: AUTH
    sshd_log_level: ERROR
    sshd_strict_modes: true
