services:

  restic:
    image: ttionya/resticprofile:0.30.1-docker
    container_name: restic
    environment:
      TZ: Europe/Berlin
      AWS_DEFAULT_REGION: eu-central-1
    entrypoint: /bin/sh
    command:
      - -c
      - export AWS_ACCESS_KEY_ID=$(cat /run/secrets/AWS_ACCESS_KEY_ID) && export AWS_SECRET_ACCESS_KEY=$(cat /run/secrets/AWS_SECRET_ACCESS_KEY) && resticprofile schedule --all && crond -f -L /dev/stdout
    healthcheck:
      test: ["CMD-SHELL", "resticprofile profiles"]
      start_period: 60s
      start_interval: 5s
      interval: 60s
      timeout: 5s
      retries: 3
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${DATA_FOLDER_PATH:-.}${DATA_FOLDER_PATH:+/restic}/log:/log
    - ${DATA_FOLDER_PATH:-.}${DATA_FOLDER_PATH:+/prometheus}/nodeexporter:/prometheus
    - ./config:/resticprofile:ro
    - ${LEVIN_DIRECTORY:-./levin}:/levin:ro
    - ${LEVIN_BACKUP_DIRECTORY:-./levin_backup}:/levin_backup
    - ${KATRIN_DIRECTORY:-./katrin}:/katrin:ro
    - ${KATRIN_BACKUP_DIRECTORY:-./katrin_backup}:/katrin_backup
    - ${SHARE_DIRECTORY:-./share}:/share:ro
    - ${SHARE_BACKUP_DIRECTORY:-./share_backup}:/share_backup
    - ${DATA_FOLDER_PATH:-./service-data}:/service-data:ro
    - ${DATA_FOLDER_BACKUP_PATH:-./service-data-backup}:/service-data_backup
    - ${SECRET_FOLDER_PATH:-./service-secrets}:/service-secrets:ro
    - ${SECRET_FOLDER_BACKUP_PATH:-./service-secrets-backup}:/service-secrets_backup
    - ${PUBLIC_DIRECTORY:-./public}:/public:ro
    - ${PUBLIC_BACKUP_DIRECTORY:-./public_backup}:/public_backup
    secrets:
    - levin_password
    - katrin_password
    - share_password
    - service-data_password
    - service-secrets_password
    - public_password
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    networks:
    - restic
    restart: unless-stopped

secrets:

  levin_password:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/restic}/levin_password
  katrin_password:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/restic}/katrin_password
  share_password:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/restic}/share_password
  service-data_password:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/restic}/service-data_password
  service-secrets_password:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/restic}/service-secrets_password
  public_password:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/restic}/public_password
  AWS_ACCESS_KEY_ID:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/restic}/AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/restic}/AWS_SECRET_ACCESS_KEY

networks:
  restic:
