services:

  restic:
    image: creativeprojects/resticprofile:0.29.0
    container_name: restic
    environment:
      TZ: Europe/Berlin
    entrypoint:
    - /bin/sh
    - -c
    - sleep 60000
    # healthcheck:
    #   test: ["CMD-SHELL", "curl --silent http://127.0.0.1:8000/ || exit 1"]
    #   start_period: 60s
    #   start_interval: 5s
    #   interval: 60s
    #   timeout: 5s
    #   retries: 3
    volumes:
    - ./config:/resticprofile:ro
    - ${LEVIN_DIRECTORY:-./levin}:/levin:ro
    - ${LEVIN_BACKUP_DIRECTORY:-./levin_backup}:/levin_backup
    - ${KATRIN_DIRECTORY:-./katrin}:/katrin:ro
    - ${KATRIN_BACKUP_DIRECTORY:-./katrin_backup}:/katrin_backup
    - ${SHARE_DIRECTORY:-./share}:/share:ro
    - ${SHARE_BACKUP_DIRECTORY:-./share_backup}:/share_backup
    - ${DATA_FOLDER_PATH:-./service-data}:/service-data:ro
    - ${DATA_FOLDER_BACKUP_PATH:-./service-data-backup}:/service-data-backup
    - ${PUBLIC_DIRECTORY:-./public}:/public:ro
    - ${PUBLIC_BACKUP_DIRECTORY:-./public_backup}:/public_backup
    secrets:
    - levin_password
    networks:
    - restic
    restart: unless-stopped

secrets:

  levin_password:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/restic}/levin_password

networks:
  restic:
