services:

  restic:
    image: creativeprojects/resticprofile:0.29.0
    container_name: restic
    environment:
      TZ: Europe/Berlin
    entrypoint:
    - /bin/sh
    - -c
    - sleep 60000
    # healthcheck:
    #   test: ["CMD-SHELL", "curl --silent http://127.0.0.1:8000/ || exit 1"]
    #   start_period: 60s
    #   start_interval: 5s
    #   interval: 60s
    #   timeout: 5s
    #   retries: 3
    volumes:
    - ./config:/resticprofile:ro
    secrets:
    - levin_password
    networks:
    - restic
    restart: unless-stopped

secrets:

  levin_password:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/restic}/levin_password

networks:
  restic:
