services:

  # Image specifies healthchecks
  filebrowser:
    image: filebrowser/filebrowser:v2.31.2
    container_name: filebrowser
    labels:
      traefik.enable: true
      traefik.http.routers.filebrowser.middlewares: authentik@docker
    entrypoint: ""
    # Auth settings can only be set via cli: https://github.com/filebrowser/filebrowser/issues/2745#issuecomment-2046607848
    # /filebrowser config set --auth.method=proxy --auth.header=X-authentik-username
    command: >
      /bin/sh -c "/filebrowser"
    volumes:
    - ./config/.filebrowser.json:/.filebrowser.json
    - ${DATA_FOLDER_PATH:-.}${DATA_FOLDER_PATH:+/filebrowser}/database:/database
    - ${LEVIN_DIRECTORY:-./levin}:/srv/levin
    - ${KATRIN_DIRECTORY:-./katrin}:/srv/katrin
    - ${PUBLIC_DIRECTORY:-./public}:/srv/public
    - ${SHARE_DIRECTORY:-./share}:/srv/share
    - ${DOWNLOAD_DIRECTORY:-./downloads}:/srv/downloads
    - ${EXTRACT_DIRECTORY:-./extract}:/srv/extract
    networks:
    - traefik
    restart: unless-stopped
