services:

  # Image specifies healthchecks
  ddnsupdater:
    image: ghcr.io/qdm12/ddns-updater:v2.9.0
    container_name: ddnsupdater
    labels:
      traefik.enable: true
      traefik.http.routers.ddnsupdater.middlewares: authentik@docker
    environment:
      CONFIG_FILEPATH: /run/secrets/ddnsupdater_config
      TZ: Europe/Berlin
    volumes:
    - ${DATA_FOLDER_PATH:-.}${DATA_FOLDER_PATH:+/ddnsupdater}/data:/updater/data
    secrets:
    - ddnsupdater_config
    networks:
    - traefik
    restart: unless-stopped

secrets:

  ddnsupdater_config:
    file: ${SECRET_FOLDER_PATH:-.}${SECRET_FOLDER_PATH:+/ddnsupdater}/config
